insert into team (
	team_name,
	division_id,
	conference_id
)
values ('Boston Celtics', 4, 2),
	('Philadelphia 76ers', 4, 2),
	('New York Knicks', 4, 2),
	('Brooklyn Nets', 4, 2),
	('Toronto Raptors', 4, 2),
	('Milwaukee Bucks', 5, 2),
	('Cleveland Cavaliers', 5, 2),
	('Chicago Bulls', 5, 2),
	('Indiana Pacers', 5, 2),
	('Detroit Pistons', 5, 2),
	('Atlanta Hawks', 6, 2),
	('Miami Heat', 6, 2),
	('Washington Wizards', 6, 2),
	('Orlando Magic', 6, 2),
	('Charlotte Hornets', 6, 2),
	('Denver Nuggets', 1, 1),
	('Minnesota Timberwolves', 1, 1),
	('Oklahoma City Thunder', 1, 1),
	('Utah Jazz', 1, 1),
	('Portland Trailblazers', 1, 1),
	('Sacramento Kings', 2, 1),
	('Phoenix Suns', 2, 1),
	('LA Clippers', 2, 1),
	('Golden State Warriors', 2, 1),
	('Los Angeles Lakers', 2, 1),
	('Memphis Grizzlies', 3, 1),
	('New Orleans Pelicans', 3, 1),
	('Dallas Mavericks', 3, 1),
	('Houston Rockets', 3, 1),
	('San Antonio Spurs', 3, 1);